name: Check File Size
on:
    push:
        branches: [main]

jobs:
    sync-to-hub:
        runs-on: ubuntu-latest
        steps:
            - name: Check large files
              uses: ActionsDesk/lfs-warning@v3.2
              with:
                  filesizelimit: 10485760 # this is 10MB so we can sync to HF Spaces
                  token: ${{ secrets.PAT_GITHUB }}
